[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader_api = "0.11.0"
x86_64 = "0.14.10"
spin = "0.9.4"
pic8259 = "0.10.2"
pc-keyboard = "0.6.1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
