[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "kernel"
test = false

[dependencies]
bootloader_api = "0.11.0"
x86_64 = "0.14.10"
spin = "0.9.4"
pic8259 = "0.10.2"
pc-keyboard = "0.6.1"
log = "0.4.17"
slab_allocator_rs = "1.0.2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
