on:
  push:
    branches: [ master ]
  pull_request:
name: check
jobs:
  fmt:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    name: ${{ matrix.os }} / fmt
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: cargo fmt --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check
  clippy:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    name: ${{ matrix.os }} / clippy
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends nasm
      - name: cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all --all-features -- -D warnings
